### ISSUE TITLE
Crashing on 1.20.1

### ISSUE THREAD

**Issue by Test-Account666** [Khajiitos/ISWYDT#1]
Hey!

I saw your mod and wanted to add it to my modpack, but it crashes.

I haven't tested it standalone, so it might be some incompatibility with other mods.

Anyway, here's the error I receive:
https://pastebin.com/fEA65k3p

Here's also a full log:
https://mclo.gs/eSzceMd

**Comment by Khajiitos** [comment]
This is weird. I just tested the mod on 1.20.1 with the exact same version of Forge you are using, and it worked fine.

The error claims the field "level" doesn't exist in the Entity class. If that was the case, you game would be gone even without the mod. Or maybe it's a weird mixin refmap issue. I doubt any other mod would mess with that, but just to be sure, can you please test the mod without other mods?

**Comment by Test-Account666** [comment]
I just tested it standalone and it still crashes:
https://mclo.gs/1oPSgYj

**Comment by Khajiitos** [comment]
This leaves me completely clueless.

The Minecraft version, Forge version and other mods should be the only variables that could cause the crash. However, even after matching these things I'm still unable to get it to crash myself.

Maybe I will find out why it crashed after staring at the crash log for more time. Regardless, thanks for reporting this!

**Comment by Test-Account666** [comment]
Hmmm, I just tried building the mod myself and now it works just fine ^^

Btw... Maybe you should add powdered snow to the list?

It isn't very effective, but still a away to cheese the neutral mobs

**Comment by Khajiitos** [comment]
Did you only test in the development environment or did you test with a built JAR too?

The time before powdered snow takes effect is quite long, but I could track that too!

**Comment by Test-Account666** [comment]
I tested it with a built jar too

**Comment by Khajiitos** [comment]
This could mean that I uploaded the wrong/broken JAR. Where did you download it from?

**Comment by Test-Account666** [comment]
I tried curseforge and modrinth

**Comment by Khajiitos** [comment]
It seems I must've uploaded the wrong files, I confirmed that the mod from CurseForge or Modrinth causes the crash. Hopefully I replaced these files with the right ones!
