### ISSUE TITLE
fails to load correctly on server when paired together with cloth config

### ISSUE THREAD

**Issue by NIMFER** [Khajiitos/ISWYDT#2]
Server fails to load your mod when it's paired with cloth config, this issue doesn't happen with Minecraft client, only with Minecraft server.

Minecraft version: 1.20.1
Mod loader: Forge 47.2.0

Cloth config version: [11.1.106](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4633444)

Log: [latest.log](https://github.com/Khajiitos/ISWYDT/files/12936510/latest.log)

**Comment by Khajiitos** [comment]
Thanks a lot for reporting this! It appears the config page is initialized even on the server-side on the Forge version, which obviously shouldn't happen. I will fix that soon!

**Comment by Khajiitos** [comment]
Latest commit should solve this issue, the updated mod will be uploaded with version 1.0.2 soon. Thanks!
