### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by nco2k** [Khajiitos/ISWYDT#4]
game crash with 1.0.3 and 1.0.4 on 1.20.4: https://pastebin.com/qPSJwA64

**Comment by Khajiitos** [comment]
I've not been able to pinpoint the issue exactly but this seems not to be happening on the 1.0.5 version of the mod. I will close the issue for now!

**Comment by nco2k** [comment]
can you please upload the latest version to modrinth? the mod is no longer crashing btw.
